sudo: required
services:
  - docker

before_install:
  - docker build -t dougmolinam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dougmolinam/react-test npm test -- --coverage

after_success:
  - docker build -t dougmolinam/multi-client ./client
  - docker build -t dougmolinam/multi-nginx ./nginx
  - docker build -t dougmolinam/multi-server ./server
  - docker build -t dougmolinam/multi-worker ./worker
  # Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to docker hub
  - docker push dougmolinam/multi-client
  - docker push dougmolinam/multi-nginx
  - docker push dougmolinam/multi-server
  - docker push dougmolinam/multi-worker